package com.pojo;
// Generated Sep 18, 2020 9:23:37 PM by Hibernate Tools 5.3.0.Beta2

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer aid;
	private String email;
	private String password;

	public Admin() {
	}

	public Admin(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public Integer getAid() {
		return this.aid;
	}

	public void setAid(Integer aid) {
		this.aid = aid;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
