package com.pojo;
// Generated Sep 18, 2020 9:23:37 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer oid;
	private Book book;
	private Register register;
	private String orderId;
	private Date orderDate;

	public Order() {
	}

	public Order(Book book, Register register, String orderId, Date orderDate) {
		this.book = book;
		this.register = register;
		this.orderId = orderId;
		this.orderDate = orderDate;
	}

	public Integer getOid() {
		return this.oid;
	}

	public void setOid(Integer oid) {
		this.oid = oid;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Register getRegister() {
		return this.register;
	}

	public void setRegister(Register register) {
		this.register = register;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

}
