package com.pojo;
// Generated Sep 18, 2020 9:23:37 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Register generated by hbm2java
 */
public class Register implements java.io.Serializable {

	private Integer rid;
	private String name;
	private String email;
	private String password;
	private String address;
	private Integer salary;
	private Set orders = new HashSet(0);

	public Register() {
	}

	public Register(String name, String email, String password, String address, Integer salary, Set orders) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.address = address;
		this.salary = salary;
		this.orders = orders;
	}

	public Integer getRid() {
		return this.rid;
	}

	public void setRid(Integer rid) {
		this.rid = rid;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getSalary() {
		return this.salary;
	}

	public void setSalary(Integer salary) {
		this.salary = salary;
	}

	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
